# Generated by Django 5.0.7 on 2024-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="appointment_date",
            new_name="treatment_date",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
