# Generated by Django 5.0.7 on 2024-08-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0002_rename_appointment_date_appointment_treatment_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="problem",
            field=models.TextField(null=True),
        ),
    ]
