# Generated by Django 5.0.7 on 2024-08-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_appointment_age"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
