# Generated by Django 5.0.6 on 2024-07-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_posts_like_alter_posts_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posts",
            old_name="Like",
            new_name="like",
        ),
    ]
