# Generated by Django 5.0.6 on 2024-06-12 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_bids_category_comments_a_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="a_listing",
            name="watchlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watch",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
