# Generated by Django 5.0.6 on 2024-06-13 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_comments_comment_comments_commentor_comments_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="bid",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="bids",
            name="bidder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bidder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="a_listing",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bidprice",
                to="auctions.bids",
            ),
        ),
    ]
