# Generated by Django 5.0.6 on 2024-06-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_bids_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bids",
            name="bid",
        ),
        migrations.RemoveField(
            model_name="bids",
            name="bidder",
        ),
        migrations.AlterField(
            model_name="a_listing",
            name="price",
            field=models.IntegerField(),
        ),
    ]
