# Generated by Django 5.0.6 on 2024-06-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_bids_bid_bids_bidder_alter_a_listing_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="blist",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
