# Generated by Django 5.0.6 on 2024-06-14 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_bids_blist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="blist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blist",
                to="auctions.a_listing",
            ),
        ),
    ]
