# Generated by Django 5.0.7 on 2024-07-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="fro",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="to",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="weeks",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
