# Generated by Django 5.0.7 on 2024-08-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="contact_number",
            field=models.PositiveIntegerField(max_length=15, null=True),
        ),
    ]
