# Generated by Django 5.0.6 on 2024-07-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_rename_like_posts_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follower",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.IntegerField(default=0),
        ),
    ]
